### PR TITLE
fix errors with ncbi_byname reported in #126

### LINKED ISSUE #126: odd errors with sequence length queries at ncbi_byname
"ncbi_byname" works great most of the time (thanks!), but with limited testing fails about 5%.  Which makes searching long lists of species cumbersome. It seems like there are some sequences in ncbii that lead to glitches, and these can be avoided by limiting the length ranges. But it is otherwise unclear why some of these queries fail consistently and other succeed or how to add options to get around it. 

I should specify that my goal is to get a longish sequence by gene/species combination. across many species and many genes (for metabarcoding primer selection).

In Rstudio.
ncbi_byname(taxa="Coryphaena hippurus", gene = c("Coi"), seqrange = "1:2000")#fails
ncbi_byname(taxa="Coryphaena hippurus", gene = c("Coi"), seqrange = "500:750")#fails
ncbi_byname(taxa="Coryphaena hippurus", gene = c("Coi"), seqrange = "600:2000")#works
ncbi_byname(taxa="Sardinops melanostictus", gene = c("12s"), seqrange = "1:2000")#fails
ncbi_byname(taxa="Sardinops melanostictus", gene = c("12s"), seqrange = "1:1000")#works
ncbi_byname(taxa="Sardinops melanostictus", gene = c("12s"), seqrange = "170:1000")#works
ncbi_byname(taxa="Sardinops melanostictus", gene = c("12s"), seqrange = "170:2000")#fails

### PR DESCRIPTION
**Pull request by dlebauer**
## Description

Fixes issues with `ncbi_byname` by
- handling batch processing
- correcting data frame structure returned by `parse_ncbi` function.
- adding regression tests for  previously reported failed cases in #126.
 
No new features

## Related Issue

fix #126

### CODE REVIEW

File: tests/testthat/test-ncbi.R [hunk 1]
```diff
@@ -0,0 +1,56 @@
...
+  expect_gte(nrow(result), 1)
+  expect_true(all(!is.na(result$taxon)))
+  expect_true(all(!is.na(result$sequence)))
+})
+
+## regression tests for https://github.com/ropensci/traits/issues/126
+
+test_that("ncbi_byname works under subset of conditions from issue #126", {
+  skip_on_cran()
+  # expect function works without error; not expect_silent that also catches messages
```
Comment (dlebauer) [inline tests/testthat/test-ncbi.R:45]:
```suggestion
```

File: tests/testthat/test-ncbi.R [hunk 2]
```diff
@@ -0,0 +1,55 @@
...
+})
+
+## regression tests for https://github.com/ropensci/traits/issues/126
+
+test_that("ncbi_byname works under subset of conditions from issue #126", {
+  skip_on_cran()
+
+  res <- ncbi_byname(taxa = "Coryphaena hippurus", gene = c("Coi"), seqrange = "1:2000")
+  expect_true(is.data.frame(res))
+  res <- ncbi_byname(taxa = "Coryphaena hippurus", gene = c("Coi"), seqrange = "1:2000")
```
Comment (dlebauer) [inline tests/testthat/test-ncbi.R:48]:
```suggestion
```
